/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author sonys
 */
public class frame2 extends javax.swing.JFrame {
    Integer kategori;
    /**
     * Creates new form frame1
     */
    public frame2() {
        initComponents();
        setVisible(true);
        kalender();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ltanggal = new javax.swing.JLabel();
        lwaktu = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        wkt = new javax.swing.JLabel();
        bMini = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        lJabatan = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 108, 0));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/frame1/logo v1.png"))); // NOI18N
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        ltanggal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ltanggal.setForeground(new java.awt.Color(255, 255, 255));
        ltanggal.setText("Tanggal ");
        header.add(ltanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 30));

        lwaktu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lwaktu.setForeground(new java.awt.Color(255, 255, 255));
        lwaktu.setText("Waktu  ");
        header.add(lwaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, 50));

        tgl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        header.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 220, 30));

        wkt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wkt.setForeground(new java.awt.Color(255, 255, 255));
        header.add(wkt, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 220, 50));

        bMini.setBackground(new java.awt.Color(255, 108, 0));
        bMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/frame1/button minimize.png"))); // NOI18N
        bMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMiniActionPerformed(evt);
            }
        });
        header.add(bMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 50, 50));

        bClose.setBackground(new java.awt.Color(255, 108, 0));
        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/frame1/button close.png"))); // NOI18N
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });
        header.add(bClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 50, 50));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 50));

        login.setFont(new java.awt.Font("DFGothic-EB", 1, 36)); // NOI18N
        login.setText("Silakan Login Sebagai");

        lJabatan.setFont(new java.awt.Font("DFGothic-EB", 1, 36)); // NOI18N
        lJabatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lPassword.setFont(new java.awt.Font("DFGothic-EB", 1, 36)); // NOI18N
        lPassword.setText("Password");

        lNama.setFont(new java.awt.Font("DFGothic-EB", 1, 36)); // NOI18N
        lNama.setText("Nama");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPasswordField1.setToolTipText("");

        jButton1.setFont(new java.awt.Font("DFGothic-EB", 0, 18)); // NOI18N
        jButton1.setText("Masuk");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lJabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lPassword)
                        .addGap(73, 73, 73)
                        .addComponent(jPasswordField1)))
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(login)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(lNama)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lJabatan)
                .addGap(86, 86, 86)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(lNama)
                    .addContainerGap(302, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 670, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BACKGROUND.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 1660, 1070));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ViewWellcome/gudang.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMiniActionPerformed
        setState(ICONIFIED);
    }//GEN-LAST:event_bMiniActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
        "Konfirmasi Keluar Aplikasi",
        "Keluar?",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
               
    }//GEN-LAST:event_bCloseActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame1 f1 =new frame1();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }
    public void kalender(){
    String [] bulan={"Januari","Febuari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"};
    while(true){
        Calendar kalender=new GregorianCalendar();
        Integer year=kalender.get(Calendar.YEAR);    
        Integer month=kalender.get(Calendar.MONTH); 
        Integer day=kalender.get(Calendar.DAY_OF_MONTH); 
        Integer jam=kalender.get(Calendar.HOUR_OF_DAY); 
        Integer menit=kalender.get(Calendar.MINUTE); 
        Integer detik=kalender.get(Calendar.SECOND); 
        String tanggal=day+" / "+ bulan[month]+" / "+ year;
        String waktu=jam+":"+menit+":"+detik;
        tgl.setText(tanggal);
        wkt.setText(waktu);
    }   
    

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bMini;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lJabatan;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel login;
    private javax.swing.JLabel ltanggal;
    private javax.swing.JLabel lwaktu;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel wkt;
    // End of variables declaration//GEN-END:variables
}
